### ISSUE TITLE
Merge `next` branch into `master`

### ISSUE THREAD

**Issue by alex-ketch** [stencila/thema#95]
This issue outlines the work we’d like to complete before merging the `next` branch into `master`.

- [x] #90: Theme editor UI
- [x] #83: Theme gallery landing page 
- [x] #71: Document theme extensions
- [ ] [Proofread/Revamp Thema README](https://github.com/orgs/stencila/projects/4#card-33640131)
- [x] Extract and migrate varius DOM manipulation patches to Encoda (issues/list need to be created)
- [ ] Change default branch to `master` again

Seems like this should be a major release version, which would necessitate updates to Encoda and Hub.
